# -*- coding: utf-8 -*-
"""27subat erenler.ipynb adlı not defterinin kopyası

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IbBqPpds5XZVh2RmKeNR3K1dr_-KTZcl
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats
from pathlib import Path

# ==============================
# SETTINGS
# ==============================
N_BINS = 20
CUTOFF = 50  # µm
GROWTH_RATES = [1, 5]  # µm/day
BOOTSTRAP_ITER = 1000

# ==============================
# LOAD DATA
# ==============================
files = {
    "Host_Plag": "/content/HG13B-PLAGResults.csv",
    "Host_Amph": "/content/HG13B-AMPH Results.csv",
    "Enclave_Plag": "/content/HG13E-PLAGResults.csv",
    "Enclave_Amph": "/content/HG13E-AMPH Results.csv"
}

# ==============================
# FUNCTIONS
# ==============================

def prepare_lengths(df, column="Feret"):
    L = df[column].values
    L = L[L >= CUTOFF]
    return L

def compute_csd(lengths):
    log_min = np.log10(lengths.min())
    log_max = np.log10(lengths.max())
    bins = np.logspace(log_min, log_max, N_BINS)

    n, edges = np.histogram(lengths, bins=bins)
    deltaL = np.diff(edges)

    mid = np.sqrt(edges[:-1] * edges[1:])

    mask = n > 0
    n = n[mask]
    deltaL = deltaL[mask]
    mid = mid[mask]

    y = np.log(n / deltaL)
    return mid, y

def linear_fit(x, y):
    # Ensure there are enough unique x values to perform regression
    if len(np.unique(x)) < 2:
        # Return infinite rss to indicate an invalid fit
        return 0, 0, 0, np.inf

    slope, intercept, r, p, stderr = stats.linregress(x, y)
    y_pred = slope * x + intercept
    rss = np.sum((y - y_pred)**2)
    return slope, intercept, r, rss

def compute_aic(rss, n, k):
    # Handle cases where rss might be infinity (from invalid linear_fit)
    if rss == np.inf:
        return np.inf
    return n * np.log(rss/n) + 2*k

def piecewise_fit(x, y):
    best_rss = np.inf
    best_break = None
    best_params = None

    # The loop range might need adjustment if N_BINS is small and leads to very few points
    # Ensure there are enough points for both segments (e.g., at least 2 points per segment)
    # Minimum i is 3, maximum is len(x)-3. This implies len(x) must be at least 6.
    if len(x) < 6: # Not enough data points to meaningfully split into two segments + boundary
        return None, None, np.inf

    for i in range(3, len(x)-3):
        x1, y1 = x[:i], y[:i]
        x2, y2 = x[i:], y[i:]

        # Perform linear fits for both segments
        s1, i1, r1, rss1 = linear_fit(x1, y1)
        s2, i2, r2, rss2 = linear_fit(x2, y2)

        rss_total = rss1 + rss2

        if rss_total < best_rss:
            best_rss = rss_total
            best_break = x[i]
            best_params = (s1, i1, s2, i2)

    return best_break, best_params, best_rss

def bootstrap_breakpoint(x, y):
    breaks = []
    for _ in range(BOOTSTRAP_ITER):
        # Ensure we don't try to resample an empty array
        if len(x) == 0:
            continue

        idx = np.random.choice(len(x), len(x), replace=True)
        xb, yb = x[idx], y[idx]

        # Filter out cases where xb might not have enough unique values for piecewise_fit
        if len(np.unique(xb)) < 6: # Need at least 6 unique points for piecewise_fit to run (range 3 to len(x)-3)
            continue

        order = np.argsort(xb)
        xb, yb = xb[order], yb[order]
        br, _, rss = piecewise_fit(xb, yb)

        # Only append a breakpoint if a valid fit was found (rss is not inf and br is not None)
        if br is not None and rss != np.inf:
            breaks.append(br)

    return np.percentile(breaks, [2.5, 97.5]) if breaks else (None, None)

def residence_time(slope):
    slope = abs(slope)
    taus = []
    for G in GROWTH_RATES:
        # Avoid division by zero if slope is zero
        if slope == 0:
            tau = np.inf
        else:
            tau = 1/(G*slope)
        taus.append(tau)
    return taus

# ==============================
# ANALYSIS
# ==============================

results = []

for name, path in files.items():

    df = pd.read_csv(path)
    lengths = prepare_lengths(df)

    # Ensure there are enough lengths after cutoff to compute CSD
    if len(lengths) < 2: # Need at least 2 points for log10(min/max) and histogram
        print(f"Skipping {name}: Not enough crystal lengths after cutoff.")
        continue

    x, y = compute_csd(lengths)

    # Ensure there are enough (x,y) points for linear and piecewise fitting
    if len(x) < 6: # Minimum required for piecewise_fit range(3, len(x)-3)
        print(f"Skipping {name}: Not enough CSD data points for fitting.")
        continue

    # Linear
    slope, intercept, r, rss_lin = linear_fit(x, y)
    aic_lin = compute_aic(rss_lin, len(x), 2)

    # Piecewise
    brk, params, rss_pw = piecewise_fit(x, y)
    aic_pw = compute_aic(rss_pw, len(x), 4)
    delta_aic = aic_lin - aic_pw

    ci_low, ci_high = bootstrap_breakpoint(x, y)

    tau_min, tau_max = residence_time(slope)

    results.append({
        "Dataset": name,
        "Slope": slope,
        "R": r,
        "AIC_linear": aic_lin,
        "AIC_piecewise": aic_pw,
        "Delta_AIC": delta_aic,
        "Breakpoint": brk,
        "CI_low": ci_low,
        "CI_high": ci_high,
        "Tau_days_minG5": tau_min,
        "Tau_days_maxG1": tau_max
    })

    # Plot
    plt.figure(figsize=(6,5))
    plt.scatter(x, y, color='black')
    plt.plot(x, slope*x+intercept, 'r', label='Linear fit')

    if delta_aic > 6 and params is not None: # Check params is not None before unpacking
        s1, i1, s2, i2 = params
        # Check if brk is not None and corresponds to a valid index
        if brk is not None and np.any(x >= brk):
            idx = np.where(x>=brk)[0][0]
            plt.plot(x[:idx], s1*x[:idx]+i1, 'b')
            plt.plot(x[idx:], s2*x[idx:]+i2, 'b', label='Piecewise')
        elif brk is None and best_rss != np.inf: # If no breakpoint but valid RSS, plot just a linear fit
             plt.plot(x, slope*x+intercept, 'r', label='Linear fit (no valid piecewise break)')

    plt.xlabel("Crystal length (µm)")
    plt.ylabel("ln(n/ΔL)")
    plt.title(name)
    plt.legend()
    plt.tight_layout()
    plt.show()

results_df = pd.DataFrame(results)
print(results_df)

import numpy as np
import matplotlib.pyplot as plt

# Datasets to visualize
datasets_to_plot = ['Host_Amph', 'Enclave_Plag', 'Enclave_Amph']

for name in datasets_to_plot:
    # Find the corresponding data in results_df
    row = results_df[results_df['Dataset'] == name].iloc[0]

    # Get the file path from the global 'files' dictionary
    file_path = files[name]

    # Re-load data and compute CSD (since x, y are not stored in results_df)
    df_current = pd.read_csv(file_path)
    lengths_current = prepare_lengths(df_current)

    # Ensure enough data points for CSD and fitting
    if len(lengths_current) < 2 or len(compute_csd(lengths_current)[0]) < 6:
        print(f"Skipping {name}: Not enough data for plotting after re-computation.")
        continue

    x_current, y_current = compute_csd(lengths_current)

    # Re-run linear and piecewise fit to get the parameters for plotting
    slope_current, intercept_current, r_current, rss_lin_current = linear_fit(x_current, y_current)
    brk_current, params_current, rss_pw_current = piecewise_fit(x_current, y_current)

    # Retrieve plotting specific values from the results_df row
    delta_aic_current = row['Delta_AIC']
    ci_low_current = row['CI_low']
    ci_high_current = row['CI_high']
    breakpoint_value = row['Breakpoint'] # Use the original breakpoint from results_df

    plt.figure(figsize=(8, 6))
    plt.scatter(x_current, y_current, color='black', label='CSD Data')
    plt.plot(x_current, slope_current * x_current + intercept_current, 'r--', label='Linear Fit')

    if delta_aic_current > 6 and params_current is not None:
        s1, i1, s2, i2 = params_current
        # Find the index for the breakpoint in the current x array
        if breakpoint_value is not None and np.any(x_current >= breakpoint_value):
            idx = np.where(x_current >= breakpoint_value)[0][0]
            plt.plot(x_current[:idx], s1 * x_current[:idx] + i1, 'b-', label='Piecewise Fit (Segment 1)')
            plt.plot(x_current[idx:], s2 * x_current[idx:] + i2, 'b-', label='Piecewise Fit (Segment 2)')
        elif breakpoint_value is None and rss_pw_current != np.inf: # Fallback if no breakpoint but valid RSS
             plt.plot(x_current, slope_current * x_current + intercept_current, 'r', label='Linear fit (no valid piecewise break)')

    # Plot breakpoint and confidence intervals
    if breakpoint_value is not None:
        plt.axvline(x=breakpoint_value, color='green', linestyle='-', linewidth=2, label=f'Breakpoint ({breakpoint_value:.2f} µm)')
    if ci_low_current is not None and ci_high_current is not None:
        plt.axvspan(ci_low_current, ci_high_current, color='green', alpha=0.1, label=f'95% CI ({ci_low_current:.2f}-{ci_high_current:.2f} µm)')

    plt.xlabel('Crystal length (µm)')
    plt.ylabel('ln(n/ΔL)')
    plt.title(f'CSD Plot for {name} with Breakpoint and CI')
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.show()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats

# ==============================
# USER SETTINGS
# ==============================

FILES = {
    "Host_Plag": "/content/G82ANAKAYA PLAGResults.csv",
    "Host_Amph": "/content/G82ANAKAYA AMPH Results.csv",
    "Enclave_Plag": "/content/G82ANKLAV PLAGResults.csv",
    "Enclave_Amph": "/content/G82ANKLAV AMPH Results.csv"
}

FERET_COLUMN = "Feret"
CUTOFF = 50
N_BINS = 20
GROWTH_RATES = [1, 5]   # µm/day
BOOTSTRAP_ITER = 1000
AIC_THRESHOLD = 6

# ==============================
# FUNCTIONS
# ==============================

def compute_csd(lengths):
    log_min = np.log10(lengths.min())
    log_max = np.log10(lengths.max())
    bins = np.logspace(log_min, log_max, N_BINS)

    n, edges = np.histogram(lengths, bins=bins)
    deltaL = np.diff(edges)
    mid = np.sqrt(edges[:-1] * edges[1:])

    mask = n > 0
    n = n[mask]
    deltaL = deltaL[mask]
    mid = mid[mask]

    y = np.log(n / deltaL)
    return mid, y

def linear_fit(x, y):
    # Ensure there are enough unique x values to perform regression
    if len(np.unique(x)) < 2:
        # Return infinite rss to indicate an invalid fit
        return 0, 0, 0, np.inf

    slope, intercept, r, p, stderr = stats.linregress(x, y)
    y_pred = slope * x + intercept
    rss = np.sum((y - y_pred)**2)
    return slope, intercept, r, rss

def compute_aic(rss, n, k):
    # Handle cases where rss might be infinity (from invalid linear_fit)
    if rss == np.inf:
        return np.inf
    return n * np.log(rss/n) + 2*k

def piecewise_fit(x, y):
    best_rss = np.inf
    best_break = None
    best_params = None

    # The loop range might need adjustment if N_BINS is small and leads to very few points
    # Ensure there are enough points for both segments (e.g., at least 2 points per segment)
    # Minimum i is 3, maximum is len(x)-3. This implies len(x) must be at least 6.
    if len(x) < 6: # Not enough data points to meaningfully split into two segments + boundary
        return None, None, np.inf

    for i in range(3, len(x)-3):
        x1, y1 = x[:i], y[:i]
        x2, y2 = x[i:], y[i:]

        # Perform linear fits for both segments
        s1, i1, r1, rss1 = linear_fit(x1, y1)
        s2, i2, r2, rss2 = linear_fit(x2, y2)

        rss_total = rss1 + rss2

        if rss_total < best_rss:
            best_rss = rss_total
            best_break = x[i]
            best_params = (s1, i1, s2, i2)

    return best_break, best_params, best_rss

def bootstrap_breakpoint(x, y):
    breaks = []

    for _ in range(BOOTSTRAP_ITER):
        # Ensure we don't try to resample an empty array
        if len(x) == 0:
            continue

        idx = np.random.choice(len(x), len(x), replace=True)
        xb, yb = x[idx], y[idx]

        # Filter out cases where xb might not have enough unique values for piecewise_fit
        if len(np.unique(xb)) < 6: # Need at least 6 unique points for piecewise_fit to run (range 3 to len(x)-3)
            continue

        order = np.argsort(xb)
        xb, yb = xb[order], yb[order]
        br, _, rss = piecewise_fit(xb, yb)

        # Only append a breakpoint if a valid fit was found (rss is not inf and br is not None)
        if br is not None and rss != np.inf:
            breaks.append(br)

    return np.percentile(breaks, [2.5, 97.5]) if breaks else (None, None)

def residence_time(slope):
    slope = abs(slope)
    taus = []
    for G in GROWTH_RATES:
        # Avoid division by zero if slope is zero
        if slope == 0:
            tau = np.inf
        else:
            tau = 1/(G*slope)
        taus.append(tau)
    return min(taus), max(taus)

# ==============================
# MAIN ANALYSIS
# ==============================

results = []

for name, file in FILES.items():

    df = pd.read_csv(file)
    lengths = df[FERET_COLUMN].values
    lengths = lengths[lengths >= CUTOFF]

    if len(lengths) < 10:
        print(f"Skipping {name}: Not enough crystal lengths after cutoff.")
        continue

    x, y = compute_csd(lengths)

    # Ensure there are enough (x,y) points for linear and piecewise fitting
    if len(x) < 6: # Minimum required for piecewise_fit range(3, len(x)-3)
        print(f"Skipping {name}: Not enough CSD data points for fitting.")
        continue

    slope, intercept, r, rss_lin = linear_fit(x, y)
    aic_lin = compute_aic(rss_lin, len(x), 2)

    brk, params, rss_pw = piecewise_fit(x, y)
    aic_pw = compute_aic(rss_pw, len(x), 4)

    delta_aic = aic_lin - aic_pw

    ci_low, ci_high = bootstrap_breakpoint(x, y)
    tau_min, tau_max = residence_time(slope)

    # ===== Plot =====
    plt.figure(figsize=(7,6))
    plt.scatter(x, y, color='black', label="CSD data")
    plt.plot(x, slope*x + intercept, 'r--', label="Linear fit")

    if delta_aic > AIC_THRESHOLD and params is not None: # Check params is not None before unpacking
        s1, i1, s2, i2 = params
        # Check if brk is not None and corresponds to a valid index
        if brk is not None and np.any(x >= brk):
            idx = np.where(x >= brk)[0][0]
            plt.plot(x[:idx], s1*x[:idx]+i1, 'b')
            plt.plot(x[idx:], s2*x[idx:]+i2, 'b', label="Piecewise")
        elif brk is None and rss_pw != np.inf: # Fallback if no breakpoint but valid RSS, plot just a linear fit
             plt.plot(x, slope*x+intercept, 'r', label='Linear fit (no valid piecewise break)')

    if brk is not None:
        plt.axvline(brk, color='green', linewidth=2, label=f"Breakpoint {brk:.1f} µm")

    if ci_low is not None:
        plt.axvspan(ci_low, ci_high, color='green', alpha=0.1,
                    label=f"95% CI {ci_low:.1f}-{ci_high:.1f}")

    plt.xlabel("Crystal length (µm)")
    plt.ylabel("ln(n/ΔL)")
    plt.title(name)
    plt.legend()
    plt.tight_layout()
    plt.show()

    results.append({
        "Dataset": name,
        "Slope": slope,
        "R": r,
        "Delta_AIC": delta_aic,
        "Breakpoint": brk,
        "CI_low": ci_low,
        "CI_high": ci_high,
        "Tau_min_days": tau_min,
        "Tau_max_days": tau_max
    })

results_df = pd.DataFrame(results)
print(results_df)